---
- name: Configure OSPF on Cisco devices
  hosts: routers  # 'routers' is the group name in the inventory file
  gather_facts: no
  connection: network_cli  # Use network_cli for network devices
  tasks:

    # Configure OSPF router ID
    - name: Configure OSPF router ID
      cisco.ios.ios_config:
        lines:
          - router ospf 1
          - router-id 1.1.1.1

    # Configure OSPF Networks for multiple subnets
    - name: Configure OSPF networks
      cisco.ios.ios_config:
        lines:
          - router ospf 1
          - network 192.168.1.0 0.0.0.255 area 0
          - network 10.0.0.0 0.0.0.255 area 0
          - network 172.16.0.0 0.0.0.255 area 1

    # Set passive interface default and enable OSPF on specific interfaces
    - name: Set passive interface default and enable on specific interfaces
      cisco.ios.ios_config:
        lines:
          - router ospf 1
          - passive-interface default
          - no passive-interface GigabitEthernet0/1
          - no passive-interface GigabitEthernet0/2

    # Set OSPF priority on interface GigabitEthernet0/1 for DR/BDR election
    - name: Set OSPF priority on an interface (for DR/BDR election)
      cisco.ios.ios_config:
        lines:
          - interface GigabitEthernet0/1
          - ip ospf priority 255

    # Configure OSPF Authentication (Message Digest) globally and on interfaces
    - name: Configure OSPF MD5 Authentication (Global and Interface)
      cisco.ios.ios_config:
        lines:
          - router ospf 1
          - area 0 authentication message-digest
          - interface GigabitEthernet0/1
          - ip ospf authentication message-digest
          - ip ospf message-digest-key 1 md5 MySecretPassword
          - interface GigabitEthernet0/2
          - ip ospf authentication message-digest
          - ip ospf message-digest-key 1 md5 AnotherSecretPassword

    # Set OSPF cost on an interface
    - name: Set OSPF cost on an interface
      cisco.ios.ios_config:
        lines:
          - interface GigabitEthernet0/2
          - ip ospf cost 10

    # Advertise the default route in OSPF
    - name: Advertise default route in OSPF
      cisco.ios.ios_config:
        lines:
          - router ospf 1
          - default-information originate

    # Configure OSPF Hello and Dead intervals on an interface
    - name: Configure OSPF Hello and Dead intervals
      cisco.ios.ios_config:
        lines:
          - interface GigabitEthernet0/1
          - ip ospf hello-interval 20
          - ip ospf dead-interval 80

    # Save the configuration to the router's memory
    - name: Save configuration
      cisco.ios.ios_command:
        command: write memory
