---
- name: Configure OSPF on Cisco devices
  hosts: routers #routers is the name of the routers with IP in the inventory file. 
  gather_facts: no
  connection: network_cli #use network cli for network devices. 
  tasks:

    - name: Configure OSPF router ID
      cisco.ios.ios_config:
        lines:
          - router ospf 1
          - router-id 1.1.1.1

    - name: Configure OSPF network
      cisco.ios.ios_config:
        lines:
          - router ospf 1
          - network 192.168.1.0 0.0.0.255 area 0

    - name: Configure OSPF passive interfaces
      cisco.ios.ios_config:
        lines:
          - router ospf 1
          - passive-interface default
          - no passive-interface GigabitEthernet0/1

    - name: Configure OSPF authentication (optional)
      cisco.ios.ios_config:
        lines:
          - router ospf 1
          - area 0 authentication message-digest
          - interface GigabitEthernet0/1
          - ip ospf authentication message-digest
          - ip ospf message-digest-key 1 md5 MySecretPassword

    - name: Save configuration
      cisco.ios.ios_command:
        command: write memory
